Feature/mappings
TeamNatron/ReleaseNotes-WebAPI pull request #73
Opened 2020-04-24 08:16 UTC by 0us

2020-04-28 13:07 UTC, markusranda requested changes
Veldig mye bra arbeid, lagt inn et par kommentara på ting som eg lur på, ha en fin dag.

2020-04-28 13:07 UTC, markusranda commented on Persistence/Contexts/DatabaseSeed.cs
> +                    {fields[5].Name, "Microsoft.VSTS.Common.StateChangeDate"},
`"System.Description"` går igjen to ganga og `{fields[1].Name, null}` såg litt rart ut, har ikke lest heile koden enda, men ska det vær sånn?

2020-04-28 13:07 UTC, markusranda commented on Persistence/Contexts/DatabaseSeed.cs
> -                    new MappableField {Name = "WorkItemId"},
Ska vi ikke lager på den?

2020-04-28 13:07 UTC, markusranda commented on Persistence/Contexts/DatabaseSeed.cs
> -                    new MappableField {Name = "WorkItemId"},
`                     new MappableField {Name = "WorkItemId"}, `

2020-04-28 13:07 UTC, markusranda commented on Persistence/Contexts/DatabaseSeed.cs
> -                    new MappableField {Name = "WorkItemId"},
` 
                    new MappableField {Name = "AuthorName"},
                    new MappableField {Name = "AuthorEmail"},`

2020-04-28 13:07 UTC, markusranda commented on Persistence/Contexts/DatabaseSeed.cs
> -                    new MappableField {Name = "WorkItemId"},
Koffer vil du ikke ha dem med "By default"?

2020-04-28 13:07 UTC, markusranda commented on Domain/Models/MappableDataTypes.cs
> +        public const string Html = "html";
Ka bi forskjellen på html og string? Førr databasen sin del så e det vel ingenting som heita HTML?

*feels confused*

2020-04-28 13:07 UTC, markusranda commented on Services/ReleaseNoteService.cs
> +                }
Liten detalj, har vært fint med enda fleire line comments, sånn at det e litt lettere å les igjønnom koden

2020-04-29 05:49 UTC, 0us commented on Persistence/Contexts/DatabaseSeed.cs
> +                    {fields[5].Name, "Microsoft.VSTS.Common.StateChangeDate"},
Ja, det va meininga. Lista blir brukt til å sette default verdia for ReleaseNoteMappings

2020-04-30 07:30 UTC, Mordi490 approved these changes

2020-04-30 09:25 UTC, 0us commented on Persistence/Contexts/DatabaseSeed.cs
> -                    new MappableField {Name = "WorkItemId"},
Fjern workitemid fordi der kun e ett reelt alterntiv til det feltet - IDen til work itemen

Fjerna authorName og authorEmail fordi det komplisera ting å ha med dei, på grunn av at dei alltid ligg inne i et "identity" objekt i azure apien. 
Går an å hardkode inn en sjekk for dei to felta `if (mappableField == "authorName") . . .`, men e syns det e så stygg løsning. Alternativt kan oss også lagre på autorName og authorEmail som ett "identity" objekt, meen det e stort arbeid. Dei to felta e heller ikkje dei viktigaste å kunne mappe, så derfor fjerna e dei

2020-04-30 09:29 UTC, 0us commented on Domain/Models/MappableDataTypes.cs
> +        public const string Html = "html";
MappableDataTypes blir også returnert i get all mappable endpointet. Syns berre det va nyttig å skille mellom string og html for brukeren sin del, sia strings og html blir behandla forskjellig i frontend.

2020-04-30 09:56 UTC, 0us commented on Services/ReleaseNoteService.cs
> +                }
Ok.

2020-04-30 10:37 UTC, markusranda commented on Domain/Models/MappableDataTypes.cs
> +        public const string Html = "html";
Aight

2020-04-30 10:38 UTC, markusranda commented on Persistence/Contexts/DatabaseSeed.cs
> -                    new MappableField {Name = "WorkItemId"},
Den er grei

2020-04-30 10:38 UTC, markusranda approved these changes

2020-04-30 10:38 UTC, merged